name: SonarQube scan
on:
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
        - uses: philips-software/sonar-scanner-action@<version>
          with:
            token: ${{ secrets.SONAR_QUBE_TOKEN }}
            projectName: hello-world
            projectKey: hello-world-app-ci-cd
            baseDir: .
            url: https://localhost:9000/
