name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  tf-destroy:
    name: 'Remove all infra'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/environments/development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}